[log]
filter = "xaynet_server::state_machine=debug,http=warn,info"

[api]
bind_address = "127.0.0.1:8081"

[pet.sum]
prob = 0.5
count = { min = 3, max = 100 }
time = { min = 20, max = 3600 }

[pet.update]
prob = 0.9
count = { min = 5, max = 10000 }
time = { min = 30, max = 3600 }

[pet.sum2]
count = { min = 1, max = 100 }
time = { min = 5, max = 3600 }

[mask]
group_type = "Prime"
data_type = "F32"
bound_type = "B2"
model_type = "M3"

[model]
length = 55117

[metrics.influxdb]
url = "http://influxdb:8086"
db = "metrics"

[redis]
# The url is configured via the enviroment variable `XAYNET_REDIS__URL`.
# `XAYNET_REDIS__URL` depends on the enviroment variable `REDIS_AUTH`,
# which is defined as a Kubernetes secret and exposed to the coordinator pod.
# See: k8s/coordinator/base/deployment.yaml

[s3]
# The access_key and secret_access_key are configured via the enviroment variables
# `XAYNET_S3__ACCESS_KEY` and `XAYNET_S3__SECRET_ACCESS_KEY`.
# See: k8s/coordinator/base/deployment.yaml
region = ["minio", "http://minio:9000"]

[restore]
enable = true
